### ISSUE TITLE
when is this releasing?

### ISSUE THREAD

**Issue by Gabiworld** [CP-Island-Localhost-Server/CPIsland_Unityproject#1]
i want to make a custom party for the game so i need the source, I also tried to decompile by myself with assetripper but it was buggy, the character didnt move but just did an animation of level up, so when is it coming out?

**Comment by R5-3600** [comment]
> i want to make a custom party for the game so i need the source, I also tried to decompile by myself with assetripper but it was buggy, the character didnt move but just did an animation of level up, so when is it coming out?

I am putting it public on here: [https://archive.org/details/cpisland-unity-project-7-1-2024.7z](https://archive.org/details/cpisland-unity-project-7-1-2024.7z)
A new version of the source code will be on there within a few days. I removed the old source code to make room for the updated copy.

**Comment by Gabiworld** [comment]
ok, ill be waiting

**Comment by R5-3600** [comment]
> ok, ill be waiting

Ok, you are welcome to join our Discord for updates: https://discord.gg/Z4WnHZ8EMH

**Comment by Gabiworld** [comment]
im already in, im whundalt, im just not talking, just there for updates on the project

**Comment by R5-3600** [comment]
> im already in, im whundalt, im just not talking, just there for updates on the project

Ah np
